# Name of your quickstart as shown on the website
name: TabOrWindowSwitching
description: >
  Always use a hard coded sleep between the click / action that triggers a new window or tab to open and attempting to switch to the new tab. 
  Monitors may receive intermittent errors due to trying to switch to the new tab before it exists without this sleep.

# Type of synthetic quickstart
# - Template (Default): Full example that users can copy paste to use
# - Snippet: Code example or building block for users to use in their own synthetic scripts
type: Snippet

# Type of synthetic monitor
# Scripted Browser = SCRIPT_BROWSER
# Scripted API = SCRIPT_API
monitorType: SCRIPT_BROWSER

# Optional: Authors of the quickstart
authors:
    - Brian P.
