# Name of your quickstart as shown on the website
name: AzureOAUTH2
description: >
  An example of authenticating against Azure using an application registration with client secret authentication configured.
  This example retrieves a value from Azure Key Vault, but similar authentication could be used to access Microsoft Graph and other Azure based resources instead. This would require modifications to the scope value in the getToken function.
  Creating the Azure application registration and setting permissions is outside of the scope of this example.
  The Azure tenant, client id / application id, and client secret should be stored as Secure Credentials.

# Type of synthetic quickstart
# - Template (Default): Full example that users can copy paste to use
# - Snippet: Code example or building block for users to use in their own synthetic scripts
type: Template

# Type of synthetic monitor
# Scripted Browser = SCRIPT_BROWSER
# Scripted API = SCRIPT_API
monitorType: SCRIPT_API

# Optional: Authors of the quickstart
authors:
    - Brian P.
