# Name of your quickstart as shown on the website
name: FTP
description: >
  Use the basic-ftp module to connect to a FTP server using a password stored in a Secure Credential,
  list the current directory contents, and close the connection. This can be extended to upload/download files, etc.

# Type of synthetic quickstart
# - Template (Default): Full example that users can copy paste to use
# - Snippet: Code example or building block for users to use in their own synthetic scripts
type: Template

# Type of synthetic monitor
# Scripted Browser = SCRIPT_BROWSER
# Scripted API = SCRIPT_API
monitorType: SCRIPT_API

# Optional: Authors of the quickstart
authors:
    - Brian P.
