# Name of your quickstart as shown on the website
name: FrameSwitching
description: >
  A small snippet showing the recommended method to switch to a frame. Frames within frames require switching a single level at a time.
  Use $driver.switchTo().defaultContent() to switch back to the main / parent frame if needed.

# Type of synthetic quickstart
# - Template (Default): Full example that users can copy paste to use
# - Snippet: Code example or building block for users to use in their own synthetic scripts
type: Snippet

# Type of synthetic monitor
# Scripted Browser = SCRIPT_BROWSER
# Scripted API = SCRIPT_API
monitorType: SCRIPT_BROWSER

# Optional: Authors of the quickstart
authors:
    - Brian P.
