# Name of your quickstart as shown on the website
name: SFTP
description: >
  Uses the ssh2-sftp-client module to connect to a SFTP server using a Secure Credential, 
  delete any previous copies of the test file, upload the test file, download the test file,
  and then delete the test file.

# Type of synthetic quickstart
# - Template (Default): Full example that users can copy paste to use
# - Snippet: Code example or building block for users to use in their own synthetic scripts
type: Template

# Type of synthetic monitor
# Scripted Browser = SCRIPT_BROWSER
# Scripted API = SCRIPT_API
monitorType: SCRIPT_API

# Optional: Authors of the quickstart
authors:
    - Brian P.
