# Name of your quickstart as shown on the website
name: ICMP
description: >
  Use the net-ping module to use ICMP to asyncrhonously ping multiple IP addresses.

# Type of synthetic quickstart
# - Template (Default): Full example that users can copy paste to use
# - Snippet: Code example or building block for users to use in their own synthetic scripts
type: Template

# Type of synthetic monitor
# Scripted Browser = SCRIPT_BROWSER
# Scripted API = SCRIPT_API
monitorType: SCRIPT_API

# Optional: Authors of the quickstart
authors:
    - Brian P.
